// Shocked Solar & Electrical - single source of truth
// All page copy, tiles, suburbs, FAQ. Edit here; everything else reads from window.CONTENT.

window.CONTENT = {
  brand: {
    name: 'Shocked Solar & Electrical',
    short: 'Shocked Solar',
    legal: 'Shocked Solar & Electrical Pty Ltd',
    abn: '27 684 898 762',
    phone_display: '0490 482 632',
    phone_tel: '0490482632',
    email: 'shockedsolarelectrical@gmail.com',
    instagram: 'https://www.instagram.com/shockedsolarandelectrical/',
    instagram_handle: '@shockedsolarandelectrical',
    base: { lat: -27.6739, lng: 152.9947, label: 'Boronia Heights' },
  },

  nav: {
    links: [
      { label: 'Services', href: '#three-pillars' },
      { label: 'Recent work', href: '#recent-work' },
      { label: 'Brands', href: '#brands' },
      { label: 'Savings', href: '#savings-calc' },
      { label: 'FAQ', href: '#faq' },
      { label: 'Quote', href: '#quote' },
    ],
    cta: 'Get a free quote',
    phone_mobile: 'Call',
  },

  hero: {
    eyebrow: '',
    // H1 rendered in three lines, middle italic + amber for emotional weight.
    h1_line1: 'Quality Brands.',
    h1_italic: 'Expert Installation.',
    h1_line3: 'Honest Pricing.',
    subhead: '',
    primary_cta: 'Get a free quote',
    secondary_cta: 'Call 0490 482 632',
    scroll_hint: 'Scroll to see the standard',
    suburb_placeholder: 'Your suburb or postcode',
    suburb_button: 'Check my suburb',
    trust_pill: '10-Year Installation Warranty',
    trust_line: 'ABN 27 684 898 762 · Shocked Solar & Electrical Pty Ltd',
    supporting_strip: ['Solar.', 'Power.', 'Comfort.'],
    photo: 'assets/gallery/10-DQlR5EGkyhf.jpg', // 100kW NQ flagship - the strongest photo
  },

  suburb_result: {
    success_template: (s) => `Yep, we cover ${s}. Lock in a free quote and we'll lock in a time.`,
    success_cta: 'Get my free quote',
    softno_template: (s) => `${s} is outside our standard run, but we travel for the bigger jobs. Give us a ring.`,
    softno_cta: 'Call 0490 482 632',
  },

  trust_strip: {
    pills: [
      'Residential + Commercial',
      'Off-grid + battery storage',
      'Airconditioning',
      'Switchboard upgrades',
      'SAA accredited installer',
      'LONGi · SolaX · GoodWe · Sungrow',
      'Pty Ltd · ABN 27 684 898 762',
    ],
  },

  three_pillars: {
    eyebrow: 'What we do',
    h2: 'Three trades. One crew. One call.',
    lead: 'Our experienced electricians provide tailored solutions for homes and businesses. Whatever the project, we have the skills, knowledge, and capability to get it done right.',
    cards: [
      {
        num: '01',
        title: 'Solar and Batteries',
        body: 'Solar and battery systems help homeowners generate, store, and use their own clean energy. By combining solar panels with battery storage, you can reduce electricity bills, increase energy independence, and keep your home powered when you need it most.',
        bullets: [
          'Residential and commercial solar installations',
          'Battery storage system design and installation',
          'Solar and battery system upgrades and expansions',
          'Battery integration with existing solar systems',
          'Inverter replacement and system upgrades',
          'System monitoring, servicing, and maintenance',
          'Fault diagnosis and repairs',
          'Expert advice on energy efficiency and energy independence',
        ],
        thumb: 'assets/gallery/10-DQlR5EGkyhf.jpg',
        icon: 'solar',
      },
      {
        num: '02',
        title: 'Airconditioning',
        body: 'Split system air conditioning delivers efficient, reliable heating and cooling for individual rooms and living spaces. Designed for year-round comfort, these systems offer quiet operation, energy efficiency, and precise temperature control, making them an ideal solution.',
        bullets: [
          'Split system installation',
          'Multi-head system installation',
          'Air conditioner replacements and upgrades',
          'Relocation of existing units',
          'Servicing and maintenance',
          'Repairs and fault finding',
          'Residential and commercial installations',
        ],
        thumb: 'assets/gallery/11-DNK4dt9TITb.webp',
        icon: 'aircon',
      },
      {
        num: '03',
        title: 'General electrical',
        body: 'General electrical services encompass the installation, maintenance, and upgrading of electrical systems across residential and commercial properties. Covering everything from lighting and power to switchboards and safety systems, these services provide tailored solutions to meet the ongoing electrical needs of any property.',
        bullets: [
          'Residential and commercial electrical installations',
          'Switchboard upgrades and safety inspections',
          'Lighting and power installations',
          'New builds and renovation wiring',
          'Electrical repairs and fault finding',
          'Smoke alarm installation and compliance',
          'Data, communication, and appliance connections',
          'Preventative maintenance and ongoing electrical servicing',
        ],
        thumb: 'assets/gallery/06-DX6gXyFCd6h.webp',
        icon: 'electrical',
      },
    ],
  },

  callback: {
    eyebrow: 'Prefer we call you?',
    h2: 'Quick call back.',
    lead: 'Drop your number and the team will ring you back. No call centre, no runaround.',
    name_ph: 'Your name',
    phone_ph: 'Your number',
    service_label: 'What about?',
    services: ['Solar + battery', 'Airconditioning', 'General electrical', 'Not sure yet'],
    cta: 'Call me back',
    success: 'Got it. The team will give you a ring shortly. Urgent? Call 0490 482 632.',
    error: "Couldn't send that. Call us on 0490 482 632 and we'll sort it.",
  },

  upgrade: {
    eyebrow: 'Already on solar?',
    h2: 'Get more out of the system you have.',
    lead: 'Most homes started with a small system. If your bills are still creeping up, there is usually more to gain. We add to and look after existing systems, not just new ones.',
    items: [
      { title: 'Add more panels', body: 'Expand an existing system to better match your current energy usage and reduce rising power bills.' },
      { title: 'Add a battery', body: 'Store excess solar energy for use at night, increase energy independence, and provide backup power during outages.' },
      { title: 'Inverter upgrade', body: 'Replace an ageing or undersized inverter with a modern, high-performance system designed for future battery integration.' },
      { title: 'Switchboard upgrade', body: 'Upgrade older switchboards to safely support solar, battery storage, and increasing electrical demands such as EV charging.' },
      { title: 'Servicing & fault-finding', body: 'Diagnose underperforming systems, resolve faults, and ensure your solar and battery system is operating at its full potential.' },
      { title: 'Grid connection & compliance', body: 'Manage all network approvals, metering requirements, and compliance paperwork to ensure a smooth and hassle-free installation.' },
    ],
    cta: 'Book a system health check',
  },

  savings: {
    eyebrow: 'Brisbane payback',
    h2: 'Drag the slider. See the savings.',
    intro: 'Based on a typical Brisbane roof receiving around 5 peak sun hours per day, current Energex network tariffs, and available federal STC rebates. Savings and payback periods will vary depending on your energy usage, electricity retailer, and system design. Book a quote for figures tailored to your home or business.',
    slider_label: 'System size',
    battery_label: 'Battery',
    battery_options: ['No battery', '13.5kWh', '27kWh'],
    out1_label: 'Estimated annual saving',
    out2_label: 'Over 25 years',
    out3_label: 'Payback in roughly',
    disclaimer: 'Indicative example only, not a Shocked price. Real numbers depend on your usage and your power plan. Your written quote has the exact figures.',
    cta: 'Book my real quote',
    // Constants for the calc (see brief component_techniques 06)
    constants: {
      PEAK_SUN_HRS: 5.0,
      HOME_USAGE_KWH: 6500,
      TARIFF_KWH: 0.30,
      FEED_IN: 0.06,
      INSTALL_COST_PER_KW: 1200,
      STC_PER_KW: 320,
      BATTERY_COST: { '0': 0, '13.5': 12500, '27': 22000 },
      BATTERY_REBATE: { '0': 0, '13.5': 4080, '27': 7140 },
      SELF_CONSUMP: { '0': 0.40, '13.5': 0.65, '27': 0.85 },
      DEGRADATION_25YR: 0.92,
    },
  },

  incentives: {
    eyebrow: 'Lower the up-front cost',
    h2: 'Upfront rebates. Straight pricing.',
    lead: 'Solar and battery systems are more affordable than most people realise once rebates are applied. Every quote clearly shows the available incentives and the final installed price. No hidden costs and no surprises.',
    tiles: [
      { name: 'Federal solar rebate', body: 'The federal Small-scale Technology Certificate (STC) scheme provides an upfront discount on eligible solar systems, reducing the cost from day one.' },
      { name: 'Federal battery rebate', body: 'The Federal Cheaper Home Batteries Program offers a discount on eligible battery installations. The rebate amount varies depending on battery size and the available incentive at the time of installation.' },
      { name: 'Feed-in tariff', body: 'Any excess energy your system exports to the grid can earn a credit on your electricity bill through your chosen energy retailer.' },
    ],
    warranty_h: 'The Shocked Warranty',
    warranty_body: 'Every system we install is backed by our 10-Year Installation Warranty, alongside the separate manufacturer warranties on your panels, inverter, and battery. We stand behind our workmanship long after the installation is complete, so you can invest with confidence.',
    finance_line: 'Finance available. Ask us about no-deposit options when you book your quote.',
    disclaimer: 'Rebates move around with your system, your retailer and the current scheme. We work out the exact figure on your written quote.',
  },

  call_band: {
    line: 'Rather just talk it through?',
    sub: 'Ring the team and get a straight answer, no pressure.',
    phone_label: 'Call 0490 482 632',
  },

  recent_work: {
    eyebrow: 'Recent work',
    h2: 'Real jobs. Real spec sheets.',
    lead: 'Every install on this page has been delivered by the team. Brand names are the kit we actually put up.',
    more_label: 'See more work',
    less_label: 'Show less',
    tiles: [
      {
        photo: 'assets/gallery/10-DQlR5EGkyhf.jpg',
        chip: '100kW · Off-grid',
        title: 'Remote NQ property',
        spec: 'Jinko panels · Schletter racking · Sigenergy inverters · 96kWh battery',
        alt: '100kW solar array on a remote North Queensland property, with Jinko panels, Schletter racking, Sigenergy inverters and 96kWh battery storage',
        feature: true,
      },
      {
        photo: 'assets/gallery/02-DYwL2LtqA1l-reel.jpg',
        chip: '21kW · Commercial',
        title: 'Mount Gravatt commercial',
        spec: 'TCL 440W panels · GoodWe 20kW 3-phase inverter',
        alt: '21kW commercial solar install in Mount Gravatt with TCL 440W panels and GoodWe 20kW 3-phase inverter',
      },
      {
        photo: 'assets/gallery/03-DYwKM2hGsQd.webp',
        chip: '13.3kW + 50kWh',
        title: 'Whole-home backup',
        spec: 'LONGi Hi-MO X10 panels · 10kW SolaX inverter · 50kWh SolaX battery',
        alt: 'Whole-home backup install with LONGi Hi-MO X10 panels, SolaX inverter and SolaX 50kWh battery',
      },
      {
        photo: 'assets/gallery/04-DYtoSH4Gue.webp',
        chip: '13.2kW · Shed',
        title: '13.2kW shed solar',
        spec: 'Clean install on the workshop roof',
        alt: '13.2kW solar system installed on a Queensland shed',
      },
      {
        photo: 'assets/gallery/07-DX6bbvVCXqV.webp',
        chip: 'Engineering',
        title: 'Landscape config for wind rating',
        spec: 'Re-worked on site, no yield lost',
        alt: 'Solar array re-configured to landscape orientation to meet wind rating compliance',
      },
      {
        photo: 'assets/gallery/11-DNK4dt9TITb.webp',
        chip: 'AC + Patio',
        title: 'Patio fit-out + AC relocation',
        spec: 'Split systems relocated, fly-over patio roughed in and fit off',
        alt: 'Two split system air conditioners relocated and patio entertainment area roughed in',
      },
      {
        photo: 'assets/gallery/20-DZt3VGxD5OZ.webp',
        alt: 'Solar panels freshly installed on a commercial roof in South-East Queensland',
      },
      {
        photo: 'assets/gallery/21-DZt3VGxD5OZ.webp',
        alt: 'Rooftop solar array on a metal roof under a clear blue Brisbane sky',
      },
      {
        photo: 'assets/gallery/22-DZJ5qM5mtr2.webp',
        alt: 'Residential solar system installed on a tin roof in South-East Queensland',
      },
    ],
  },

  brands: {
    eyebrow: 'Our preferred brands',
    h2: 'Gear we <em class="italic-serif">stand behind</em>.',
    lead: 'The gear we actually install, across all three trades. Tap a category to see the brands.',
    groups: [
      { key: 'panels', category: 'Solar panels', items: [
        { brand: 'LONGi', product: 'Hi-MO X10 panels', logo: 'assets/brands/longi.svg' },
        { brand: 'Trina', product: 'Vertex high-output panels', logo: 'assets/brands/trina.svg' },
        { brand: 'TCL', product: '440W high-efficiency', logo: 'assets/brands/tcl.svg' },
        { brand: 'Jinko', product: 'High-output mono panels', logo: 'assets/brands/jinko.svg' },
      ]},
      { key: 'inverters', category: 'Inverters', items: [
        { brand: 'SolaX', product: 'Hybrid inverters', logo: 'assets/brands/solax.png' },
        { brand: 'GoodWe', product: '3-phase inverters', logo: 'assets/brands/goodwe.svg' },
        { brand: 'Sungrow', product: 'String + hybrid', logo: 'assets/brands/sungrow.svg' },
        { brand: 'Sigenergy', product: 'Hybrid inverter + storage', logo: 'assets/brands/sigenergy.webp' },
      ]},
      { key: 'batteries', category: 'Batteries', items: [
        { brand: 'SolaX', product: 'Triple Power, up to 50kWh', logo: 'assets/brands/solax.png' },
        { brand: 'Sigenergy', product: 'Modular storage', logo: 'assets/brands/sigenergy.webp' },
      ]},
      { key: 'racking', category: 'Racking', items: [
        { brand: 'Schletter', product: 'Wind-rated mounting', logo: 'assets/brands/schletter.svg' },
        { brand: 'Clenergy', product: 'Rail mounting systems', logo: 'assets/brands/clenergy.svg' },
        { brand: 'Antai', product: 'Mounting systems', logo: 'assets/brands/antai.svg' },
        { brand: 'PowerWave', product: 'Roof mounting', logo: 'assets/brands/powerwave.png', lh: 34 },
      ]},
      { key: 'aircon', category: 'Airconditioning', items: [
        { brand: 'Mitsubishi', product: 'Split systems', logo: 'assets/brands/mitsubishi.svg', lh: 24 },
        { brand: 'Daikin', product: 'Split + multi-head', logo: 'assets/brands/daikin.svg', lh: 22 },
      ]},
      { key: 'electrical', category: 'General electrical', items: [
        { brand: 'Clipsal', product: 'Switches + power points', logo: 'assets/brands/clipsal.svg' },
        { brand: 'Schneider Electric', product: 'Switchboards + protection', logo: 'assets/brands/schneider.svg', lh: 22 },
        { brand: 'Legrand', product: 'Wiring accessories', logo: 'assets/brands/legrand.svg', lh: 26 },
        { brand: 'Atom', product: 'Electrical accessories', logo: 'assets/brands/atom.png' },
      ]},
    ],
    creds: [
      { type: 'shield', label: 'SAA Accredited Installer', meta: 'Solar Accreditation Australia', id: 'S4689636' },
      { type: 'cert', label: 'Electrical Contractor Licence', meta: 'Queensland', id: '1508323' },
    ],
    footnote: 'We confirm the exact make and model of every component on your written quote.',
  },

  process: {
    eyebrow: 'How it runs',
    h2: 'From first call to clean handover.',
    lead: "Here's exactly how a Shocked Solar & Electrical job runs, whether it's solar, batteries, air conditioning, or general electrical work. No surprises, just a straightforward process from start to finish.",
    steps: [
      { num: '01', title: 'Free Quote & Site Inspection', body: 'We assess your property, discuss your requirements, and provide a detailed quote with all available rebates and options clearly explained.' },
      { num: '02', title: 'Design & Planning', body: 'Every system is designed to suit your needs. We handle the paperwork, approvals, and technical details so the process is simple and stress-free.' },
      { num: '03', title: 'Professional Installation', body: 'The same team that quotes your job carries out the installation, delivering tidy workmanship, quality products, and attention to detail on every project.' },
      { num: '04', title: 'Testing & Handover', body: 'Every installation is thoroughly tested and commissioned before handover. We walk you through the system, answer any questions, and leave your property clean and ready to go.' },
    ],
  },

  service_area: {
    eyebrow: 'Service area',
    h2: 'Where the team works.',
    lead: '',
    clusters: [
      { name: 'Moreton Bay & Redcliffe', items: 'Redcliffe · Scarborough · Margate · Clontarf · North Lakes · Sandgate' },
      { name: 'Brisbane south', items: 'Mount Gravatt · Sunnybank · Salisbury · Moorooka · Tarragindi · Carindale' },
      { name: 'Logan', items: 'Browns Plains · Boronia Heights · Springwood · Beenleigh · Loganholme · Daisy Hill' },
      { name: 'Ipswich', items: 'Springfield · Goodna · Camira · Bellbird Park · Gailes' },
      { name: 'Scenic Rim & Tamborine', items: 'Jimboomba · Greenbank · Yarrabilba · Flagstone · Tamborine · Canungra' },
      { name: 'Gold Coast & Tweed', items: 'Southport · Burleigh · Palm Beach · Coolangatta · Tweed Heads (NSW)' },
    ],
    softno: 'Outside the run? For commercial and off-grid jobs the team travels. Ring 0490 482 632 and we will sort it.',
  },

  quote: {
    eyebrow: 'Free quote',
    h2: 'Tell us about the job.',
    lead: 'Tell us about the job and the team will get back to you to lock in a time.',
    sla: 'We reply to every quote request, usually the same business day.',
    fields: {
      name: 'Your name',
      phone: 'Phone',
      email: 'Email',
      suburb: 'Suburb or postcode',
      interests_label: 'What are you after?',
      interests: ['Solar + battery', 'Airconditioning', 'General electrical', 'Not sure yet'],
      message: 'Tell us about the job (optional)',
      referral_label: 'How did you hear about us? (optional)',
      referrals: ['Google', 'Instagram or Facebook', 'A mate or referral', 'Saw a job nearby', 'Other'],
    },
    consent: 'By sending this you agree to be contacted about your quote. We will never share your details.',
    cta: 'Send to the team',
    success_h: 'Got it.',
    success_body: "Cheers, the team will be in touch shortly. If it's urgent give us a bell on 0490 482 632.",
    error_body: "Couldn't send that one. Try again, or call us on 0490 482 632 and we'll sort it.",
  },

  faq: {
    eyebrow: 'FAQ',
    h2: 'Straight answers.',
    side_cta: 'Still got a question? Ring the team on 0490 482 632.',
    items: [
      { q: 'Why should I go solar now?', a: 'Power prices keep climbing, and the Queensland sun does the heavy lifting. A well-sized system can cut your bills from day one, reduce your reliance on the grid, and pair with a battery to keep essential circuits running during outages. We will tell you honestly whether solar stacks up for your property.' },
      { q: 'Do I still get the federal solar rebate?', a: 'Yes. The federal Small-scale Technology Certificate (STC) scheme is currently available on eligible new systems and is applied as an upfront discount on your quote, not a rebate you chase later. We will explain exactly what your system qualifies for before you sign anything.' },
      { q: 'What about the battery rebate?', a: 'Yes. The Federal Cheaper Home Batteries Program is available on eligible battery installations. The value depends on the battery size and the scheme settings at the time of installation, so we calculate it at quote time and show it as a separate line item.' },
      { q: 'Do I really need a battery, or just panels?', a: 'That depends on your energy usage, electricity bills, and whether backup power matters to you. We have installed everything from panels-only systems to whole-home backup with 50kWh battery systems. You will get honest advice, not a sales pitch.' },
      { q: 'What does the 10-Year Installation Warranty cover?', a: 'Everything we install. The full scope, exclusions, and call-out terms are clearly outlined in your written quote, alongside the separate manufacturer warranties on panels, inverters, and batteries.' },
      { q: 'Are you accredited and licensed?', a: 'Yes. We are accredited with Solar Accreditation Australia (SAA S4689636) and hold Electrical Contractor Licence 1508323. Every installation is completed to those standards.' },
      { q: 'What brands do you install?', a: 'We install a wide range of proven products, including LONGi, Trina, TCL and Jinko panels; SolaX, GoodWe, Sungrow and Sigenergy inverters; SolaX and Sigenergy batteries; Schletter, Clenergy, Antai and PowerWave racking; Mitsubishi and Daikin air conditioning; and Clipsal, Schneider, Legrand and Atom electrical products. Tap through them in the brands section above.' },
      { q: 'How do you choose the right equipment?', a: 'We match the system to your roof, your budget, and how you actually use power, not whatever happens to be sitting in the shed. The exact equipment and the reason we have recommended it are detailed in your written quote.' },
      { q: 'Can you do off-grid or remote properties?', a: 'Yes. We have delivered a 100kW off-grid system on a remote North Queensland property with 96kWh of battery storage. Big or small, on-grid or off-grid, we can design for it.' },
      { q: 'Can you upgrade my switchboard at the same time as solar?', a: 'Often, yes. Many older homes need a switchboard upgrade before solar or batteries can be installed safely. If that is the case, we will identify it upfront and include it in the quote. One crew, one visit, no surprises.' },
      { q: 'How do I know what size air conditioning I need?', a: 'Room size, insulation, ceiling height, window orientation, and occupancy all matter. We assess the space on-site and size the system properly to ensure efficient, long-term performance.' },
      { q: 'Can you relocate or add a split system during a renovation?', a: 'Absolutely. We have relocated air conditioning systems to make way for major renovations and completed the associated electrical works at the same time. If you are renovating, we can incorporate it into the project.' },
      { q: 'What electrical work do you do beyond solar?', a: 'Everything from lighting and power installations to kitchen appliances, switchboards, patios, entertainment areas, and commercial electrical work. If it needs a licensed electrician, we can help.' },
      { q: 'How long does an installation take?', a: 'Most residential solar systems are completed in a single day once approvals and materials are in place. Larger systems and battery installations may take two to three days. We will provide a realistic timeline in your quote.' },
      { q: 'Will my system keep working during a blackout?', a: 'With the right battery setup, yes. A standard solar system shuts down during a blackout for safety reasons, but a battery with backup capability can keep essential circuits, or even the whole home, running.' },
      { q: 'Do you handle insurance and warranty repairs?', a: 'Yes. We can assess damaged systems, assist with warranty claims, and carry out repairs where required.' },
      { q: 'What areas do you cover?', a: 'From Redcliffe to Tweed Heads in the south, across South-East Queensland and remote projects by arrangement. If you are unsure, give us a call and we will confirm your area.' },
    ],
  },

  footer: {
    brand_tag: 'Solar, air conditioning and electrical for South-East Queensland and Northern NSW. Powered the right way.',
    services_h: 'Services',
    services_items: ['Solar + battery', 'Off-grid solar', 'Airconditioning', 'General electrical', 'Commercial installs', 'Whole-home backup'],
    areas_h: 'Service area',
    areas_items: ['Moreton Bay & Redcliffe', 'Brisbane south', 'Logan', 'Ipswich', 'Gold Coast & Tweed', 'Larger jobs (wider SEQ + NQ)'],
    contact_h: 'Contact',
    legal_line: 'Shocked Solar & Electrical Pty Ltd · ABN 27 684 898 762 · SAA accredited S4689636 · Electrical licence 1508323',
    copyright: '© 2026 Shocked Solar & Electrical Pty Ltd. All rights reserved.',
    credit: 'Built by Applied Intelligence',
  },

  mobile_call_bar: {
    label: 'Call 0490 482 632',
    aria_label: 'Call Shocked Solar and Electrical on 0490 482 632',
  },

  micro_copy: [
    "Nothing we can't handle.",
    'Same kit. Same crew. Same warranty.',
    'Real jobs. Real spec sheets.',
    'Drag the slider. See the savings.',
    'Big jobs. Small jobs. Clean installs.',
    'Quality kit. Honest pricing.',
    'Sized right. Mounted clean.',
    'Roughed in. Fit off. Tested under load.',
    'Tell us about the job.',
    'Lock in a time that suits.',
    'Call the team. 0490 482 632',
  ],

  // Service-area suburbs the team covers, Redcliffe in the north to Tweed Heads in the south.
  // Used by the suburb-check combobox. Order alphabetised.
  suburbs: [
    'Acacia Ridge','Algester','Annerley','Archerfield','Bahrs Scrub','Bannockburn','Beenleigh','Belivah','Bellbird Park','Berrinba',
    'Bethania','Bilinga','Boronia Heights','Bracken Ridge','Brighton','Broadbeach','Browns Plains','Buccan','Burleigh Heads','Calamvale',
    'Camira','Carbrook','Carindale','Cedar Grove','Cedar Vale','Chambers Flat','Cleveland','Clontarf','Coolangatta','Coomera',
    'Coopers Plains','Cornubia','Crestmead','Currumbin','Daisy Hill','Deception Bay','Drewvale','Eagleby','Edens Landing','Eight Mile Plains',
    'Ellen Grove','Flagstone','Forestdale','Forest Lake','Gailes','Goodna','Greenbank','Griffin','Heritage Park','Hillcrest',
    'Holland Park','Holmview','Inala','Ipswich','Jimboomba','Kallangur','Kingston','Kippa-Ring','Kirra','Kuraby',
    'Larapinta','Logan Central','Loganholme','Loganlea','Logan Reserve','Mackenzie','Macleay Island','Mango Hill','Mansfield','Margate',
    'Marsden','Meadowbrook','Mermaid Beach','Miami','Moorooka','Mount Cotton','Mount Gravatt','Mount Warren Park','Mundoolun','Munruben',
    'Murrumba Downs','Nerang','New Beith','Newport','North Lakes','North Maclean','Oxley','Pallara','Palm Beach','Park Ridge',
    'Park Ridge South','Parkinson','Petrie','Priestdale','Redbank','Redbank Plains','Redcliffe','Regents Park','Richlands','Robina',
    'Rochedale','Rochedale South','Rothwell','Runcorn','Russell Island','Salisbury','Sandgate','Scarborough','Shailer Park','Shorncliffe',
    'Slacks Creek','South Maclean','Southport','Spring Mountain','Springfield','Springfield Central','Springfield Lakes','Springwood','Stockleigh','Stretton',
    'Sunnybank','Sunnybank Hills','Surfers Paradise','Tallebudgera','Tamborine','Tanah Merah','Tarragindi','Tugun','Tweed Heads','Tweed Heads South',
    'Underwood','Varsity Lakes','Veresdale','Waterford','Waterford West','Wishart','Woodridge','Woody Point','Yarrabilba','Yeronga',
  ],
};
